project_id = "knztycdtgqgoncjhgawq"

[functions.setup-admin]
verify_jwt = false

[functions.translate-name]
verify_jwt = true

[functions.translate-text]
verify_jwt = true

[functions.create-teacher]
verify_jwt = true

[functions.admin-impersonate-teacher]
verify_jwt = true

[functions.check-course-expiry]
verify_jwt = true

[functions.teacher-course-mapping]
verify_jwt = true
